name: PlayerPointsTime
main: com.gmail.falistos.PlayerPointsTime.PlayerPointsTime
version: 0.1.1
commands:
    pointstime:
        description: Manage PlayerPointsTime
depend: [Vault,PlayerPoints]